"""Add created_by to shares

Revision ID: 15fad472caa2
Revises: 50d9771872f6
Create Date: 2026-01-28 23:29:24.491654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fad472caa2'
down_revision = '50d9771872f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_shares_created_by_users', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shares_created_by_users', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
