"""Rename url field to store_url in DiscountCode model

Revision ID: 212198c7684d
Revises: c8099cb8429e
Create Date: 2026-01-11 17:42:07.374458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212198c7684d'
down_revision = 'c8099cb8429e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('store_url')

    # ### end Alembic commands ###
