"""Add visit_count to shares

Revision ID: 50d9771872f6
Revises: 59232c2c1304
Create Date: 2026-01-28 22:51:46.885941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d9771872f6'
down_revision = '59232c2c1304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_column('visit_count')

    # ### end Alembic commands ###
