"""Make user_id not nullable

Revision ID: 59232c2c1304
Revises: e4b19a504c47
Create Date: 2026-01-12 17:17:41.707170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59232c2c1304'
down_revision = 'e4b19a504c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
