"""Add user_id to discount_codes

Revision ID: 5a40cb7c6d53
Revises: 69a7bf15c9d1
Create Date: 2026-01-12 17:09:39.119837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a40cb7c6d53'
down_revision = '69a7bf15c9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_discount_codes_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discount_codes_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
