"""Add URL field to DiscountCode model

Revision ID: c8099cb8429e
Revises: ab8e45450158
Create Date: 2026-01-11 14:41:47.782924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8099cb8429e'
down_revision = 'ab8e45450158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
